# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807f1016caf8dbac7ba93d0bb8b9e296df2f9c580181558db49b3546b4970df987873a12ed4fa31f83fa644cf78d537bebc3171d0d37b1cedc0dea39b8de774e

test:
  secret_key_base: 6a7a4d8c902a221e86c4bdb6c3fa519066936663e6ce44a0faec5fcfaaec94bf3103f365e8213888c9ee6a258410d449e99f6d0dfcb66a7c0cbe47edfb07d227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
